"""removing reputations of loans , projects , savings from the student model

Revision ID: 4195441fde6b
Revises: dcf64adff9ea
Create Date: 2025-03-12 16:27:34.536315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4195441fde6b'
down_revision = 'dcf64adff9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('projects')
        batch_op.drop_column('loans')
        batch_op.drop_column('savings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('loans', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('projects', mysql.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
