"""adding the balance column to the savings model

Revision ID: a039d306c7b7
Revises: ed8b6d27ce1f
Create Date: 2025-03-31 13:44:03.432313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a039d306c7b7'
down_revision = 'ed8b6d27ce1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
