"""Initial migration

Revision ID: dcf64adff9ea
Revises: 
Create Date: 2025-03-12 15:50:54.152857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf64adff9ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('savings', sa.Float(), nullable=True),
    sa.Column('loans', sa.Float(), nullable=True),
    sa.Column('projects', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('collateral', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('penalty_rate', sa.Float(), nullable=True),
    sa.Column('repayment_deadline', sa.Date(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_funds', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings')
    op.drop_table('projects')
    op.drop_table('loans')
    op.drop_table('student')
    # ### end Alembic commands ###
