"""adding the different foreigmKeys (loans, withdrawals, projects) to the notifications model

Revision ID: e7807d8da33d
Revises: 8c35762df1a0
Create Date: 2025-04-02 01:48:33.095564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7807d8da33d'
down_revision = '8c35762df1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('loan_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('withdrawal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'loans', ['loan_id'], ['id'])
        batch_op.create_foreign_key(None, 'withdrawals', ['withdrawal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('withdrawal_id')
        batch_op.drop_column('loan_id')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
