"""commenting out the status , and transaction type on the savings' model

Revision ID: ed8b6d27ce1f
Revises: 4195441fde6b
Create Date: 2025-03-13 13:22:00.037419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed8b6d27ce1f'
down_revision = '4195441fde6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', mysql.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
